name: pytest and flake8

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change the Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this command based on how you manage your dependencies
    - name: Install requirements
      run: |
        ls
        pwd
        cat solution/data/census_clean.csv
        pip install -e .
    - name: Run ruff
      run: |
        ruff check --fix

    - name: Run Flake8
      run: |
        flake8 . --ignore=E501,W503

    - name: Run pytest
      run: |
        pytest -s solution/test_ml_model.py
#        python -m pytest solution/test_ml_model.py
