name: pytest and flake8

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change the Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this command based on how you manage your dependencies
    - name: Run ruff
      run: |
        ruff check --fix

    - name: Run Flake8
      run: |
        flake8 . --ignore=E501,W503

    - name: Run pytest
      run: |
        pytest -s solution/test_ml_model.py

    - name: Upload container to AWS
      if: ${{ success() }}
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-east-1
      run: |
        sh upload_container.sh

