name: Upload container to ECR

on:
  push:
    branches:
      - master

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload container to AWS
      run: |
        sh upload_container.sh